[package]
name = "sdf-viewer"
version = "0.0.1"
authors = ["Yeicor <yeicor1212@gmail.com>"]
license = "MIT or Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Required for web (and Android...)

[dependencies]
# Three-D git is only needed for 40a6fa968381c6bdb4a7e36e7aea67a65a4b3b43
three-d = { git = "https://github.com/asny/three-d", default-features = false, features = ["canvas"] }
log = "0.4"
eframe = "0.18.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies] # Native dependencies (including mobile)
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }

[target.'cfg(target_os = "android")'.dependencies] # Android dependencies
ndk-glue = "0.6"
# HACK: force-enable vendored OpenSSL sources for android builds (keep version in sync?)
openssl = { version = "*", features = ["vendored"] }

[target.'cfg(target_arch = "wasm32")'.dependencies] # Web dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "0.2"

[profile.release]
lto = true
codegen-units = 1

[package.metadata.android]
label = "SDF Viewer"
opengles_version_major = 3
opengles_version_minor = 0
# TODO: build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false # https://github.com/rustwasm/wasm-pack/issues/781

[patch.crates-io]
# HACK: "small" patches to "build" and "run" for android (probably breaking stuff)
# FIXME: Android builds and runs, but does not show anything to screen (no crashes!)...
# TODO: Wait for official support (https://github.com/rust-windowing/glutin/pull/1385#issuecomment-1138894794)
glutin = { git = "https://github.com/Yeicor/glutin" }
arboard = { git = "https://github.com/Yeicor/arboard" }
# Update ndk-glue dependency of winit
winit = { git = "https://github.com/rust-windowing/winit" }
