[package]
name = "sdf-viewer"
version = "0.0.1"
authors = ["Yeicor <yeicor1212@gmail.com>"]
license = "MIT or Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Required for WebAssembly (and Android...)

[dependencies]
three-d = "0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "0.2"
