# Release workflow builds the release executables for all platforms and publishes them to GitHub
name: Release builds

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write # Required to upload artifacts to releases (and pushing the version update)

jobs:
  update-cargo-version:
    name: Update the version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master' # HACK: Should be the tag, but we are making a push to master
      - name: Auto-update Cargo.toml and move the release tag
        id: auto-update
        run: |
          export VERSION="${GITHUB_REF##*/}"
          sed -E -i "s/^version = \"[0-9]+(\.[0-9]+){1,2}\"/version = \"${VERSION:1}\"/g" Cargo.toml  # e.g. v0.0.1 -> version = "0.0.1"
          # cargo tree  # Check that we did not break the Cargo.toml
          git config --global user.email "yeicor@users.noreply.github.com"
          git config --global user.name "Yeicor"
          if git commit -am "Update Cargo.toml to version ${VERSION:1} (automatic)"; then
            # Move the tag to the new commit
            git tag -f -a "$VERSION" -m "$VERSION"
            git push -f --tags # Force push the tag to GitHub
            # The tag move will trigger a new workflow, so stop this one
            echo -e "\n::set-output name=CANCEL_WORKFLOW::true"
          else
            echo "No change to the Cargo.toml version, performing the build on the moved tag"
          fi
      - name: Cancel the workflow if the tag was moved (new workflow started)
        if: ${{ steps.auto-update.outputs.CANCEL_WORKFLOW == 'true' }}
        uses: andymckay/cancel-action@0.2
  deploy-linux:
    name: Release
    runs-on: '${{ matrix.os }}'
    needs:
      - update-cargo-version
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
            pre: sudo apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
          # TODO: Mac OS x86_64
          #          - os: macos-latest
          #            target: x86_64-apple-darwin
          #            pre: brew install libx11 libxi
          #            post: TODO: (pack a .dmg?)
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: exe
          # Web (WebAssembly)
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
            ext: tar.gz  # After post-processing
            pre: rustup target add wasm32-unknown-unknown && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            build: wasm-pack build --target web --out-dir ./target/pkg
            post: ".github/scripts/release-wasm-post.sh ./target/pkg/${GITHUB_REPOSITORY#*/}.wasm"
          # Android
          - os: ubuntu-latest
            target: android  # Multiple architectures are supported
            pre: rustup target add aarch64-linux-android && cargo install cargo-apk
            build: cargo apk build --release --lib
            ext: apk
          # TODO: iOS
    #          - os: macos-latest
    #            target: ???
    #            pre: ???
    #            build: ???
    #            post: ???
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1.3.0
        with:
          key: ${{ matrix.os }}-${{ matrix.target }}
      - uses: nttld/setup-ndk@v1
        if: ${{ matrix.target == 'android' }}
        with:
          ndk-version: r21e

      - name: Preparing for build
        if: ${{ matrix.pre != '' }}
        run: ${{ matrix.pre }}

      - name: Release build
        if: ${{ matrix.build == '' }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target ${{ matrix.target }}
      - name: Release build
        if: ${{ matrix.build != '' }}
        run: ${{ matrix.build }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          PKG_CONFIG_SYSROOT_DIR: ${{ steps.setup-ndk.outputs.ndk-path }}/sysroot

      - name: Postprocessing after build
        if: ${{ matrix.post != '' }}
        run: ${{ matrix.post }}
      - name: Prepare release
        id: prepare-release
        shell: bash
        run: |
          set -ex
          build_name="${{ matrix.build_name }}"
          exe_name="${GITHUB_REPOSITORY#*/}-${GITHUB_REF##*/}-${{ matrix.target }}-${GITHUB_SHA:0:7}"
          if [[ -z "$build_name" ]]; then  # Default build name: <repo-name>.<extension>
            if [[ -z "${{ matrix.ext }}" ]]; then
              build_name="${GITHUB_REPOSITORY#*/}"
            else
              build_name="${GITHUB_REPOSITORY#*/}.${{ matrix.ext }}"
              exe_name="$exe_name.${{ matrix.ext }}"
            fi
          fi
          # Make sure we own all files (for Docker)
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then sudo chown -R $(id -u):$(id -g) target; fi
          # Find and copy the release binary
          find target -type f -name "$build_name" -printf '%p' -exec mv {} "${exe_name}" \;
          echo -e "\n::set-output name=EXE_NAME::${exe_name}"
          du -h "${exe_name}"
      - name: Publish the release build
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.prepare-release.outputs.EXE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare static site (only for web builds)
        if: ${{ matrix.target == 'wasm32-unknown-unknown' }}
        run: mkdir public && tar -xvzf "${{ steps.prepare-release.outputs.EXE_NAME }}" --directory public
      - name: Deploy static site (only for web builds)
        if: ${{ matrix.target == 'wasm32-unknown-unknown' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: public
